### ISSUE TITLE
The Variable "segSize" does not exist

### ISSUE THREAD

**Issue by Bichtslap** [no-carrier/ProcessingTextmodeEngine#3]
Sorry for asking this i'm a noob at programing, i download the zip and open it with the latest version of Processing for Windows 64 bits.When i run the code there are a lot of errors Mainly
The Variable "segSize" does not exist
The Variable "b" does not exist
The Variable "blockMode" does not exist
Can anyone explain to me how to make this work?

I'm on Windows 7 Ultimate 64 bits

Thanks

Screenshot:
http://puu.sh/p0CBf/6fa364395e.png

**Comment by no-carrier** [comment]
Hey, no worries! Looks like you clicked on / dragged in one of the PDE source files. I'd recommend opening "ProcessingTextmodeEngine.pde" in Processing, by clicking on it in the folder. It should open that PDE and the you have open currently, in two tabs. Then try hitting the PLAY button at the top.

For some reason, you only have the one PDE file open, which is why it doesn't think any of those variables exist (as they are defined in the other file).

Let me know if that works!

**Comment by Bichtslap** [comment]
I re-extracted de rar file and got the folder with the 2 .pde files when i open the file the processing says to me "http://puu.sh/p1esr/9288791f17.png" if i hit cancel then it says "http://puu.sh/p1evq/ce62b52c6a.jpg" and if i click ok then it open the file and move it to a new folder with the name of "ProcessingTextmodeEngine" and open this "http://puu.sh/p1ePS/7c13c44553.png"(on the left side is the folder with the arhives when i click on open)

Hope you understand me , sorry for the bad English
Thanks for the support :+1:

**Comment by no-carrier** [comment]
OK, I see the problem. When you "download" instead of "clone", it downloads "ProcessingTextmodeEngine-master.zip". Please rename this to "ProcessingTextmodeEngine.zip". So, remove the "-master" part. Then extract and click on ProcessingTextmodeEngine.pde.

In Processing, the folder name should be "ProcessingTextmodeEngine" and the PDE has to be the same: "ProcessingTextmodeEngine.pde". They always have to match.

Please let me know if this works.

**Comment by Bichtslap** [comment]
Yesss, Perfect it worked great, thanks for your help, nice software

**Comment by no-carrier** [comment]
Nice, enjoy!!! 👍
